- name: Check existence of container
  command: podman container exists jellyfin
  register: container_exists
  failed_when: container_exists.rc > 1

- name: Create media directory
  file:
    path: "{{ mediadir }}"
    state: directory

- name: Create container
  command: >
    podman create --name=jellyfin -e PUID=1000 -e PGID=1000 -p 8096:8096 -p
    8920:8920 -p 7359:7359/udp -p 1900:1900/udp -v jellyfin-config:/config -v {{
    mediadir }}/shows:/media/shows -v {{ mediadir }}/movies:/media/movies
    lscr.io/linuxserver/jellyfin:latest
  when: container_exists.rc == 1

- name: Configure firewalld
  firewalld:
    service: jellyfin
    state: enabled
    immediate: true
    permanent: true
  become: true

- name: Install systemd service
  copy:
    src: jellyfin.service
    dest: "{{ configdir }}/systemd/user/jellyfin.service"
    mode: 0644

- name: Enable systemd service
  systemd:
    name: jellyfin.service
    scope: user
    state: started
    enabled: true
    daemon_reload: true

- name: Install easymode config
  copy:
    src: jellyfin.yml
    dest: "{{ easymodeconfig }}/"
  when: easymodeconfig is defined
