- name: Check existence of container
  command: podman container exists easymode
  register: container_exists
  failed_when: container_exists.rc > 1

- name: Create container
  command: >
    podman create --name=easymode
    -p 80:80
    -e EASYMODE_HOSTNAME={{ ansible_hostname }}
    -e EASYMODE_IP={{ hostip }}
    -v {{ easymodeconfig }}:/config:z
    docker.io/supplantr/easymode
  when: container_exists.rc == 1

- name: Configure sysctl
  sysctl:
    name: net.ipv4.ip_unprivileged_port_start
    value: '80'
    sysctl_set: yes
    state: present
    reload: yes
  become: true

- name: Configure firewalld
  firewalld:
    port: '{{ item }}'
    state: enabled
    immediate: true
    permanent: true
  loop:
    - 80/tcp
  become: true

- name: Install systemd service
  copy:
    src: easymode.service
    dest: '{{ configdir }}/systemd/user/easymode.service'
    mode: 0644

- name: Enable systemd service
  systemd:
    name: easymode.service
    scope: user
    state: started
    enabled: true
    daemon_reload: true
