- name: Check existence of container
  command: podman container exists heimdall
  register: container_exists
  failed_when: container_exists.rc > 1

- name: Create container
  command: >
    podman create --name=heimdall
    -p 80:80
    -p 443:443
    -v heimdall-config:/config
    docker.io/linuxserver/heimdall
  when: container_exists.rc == 1

- name: Configure sysctl
  sysctl:
    name: net.ipv4.ip_unprivileged_port_start
    value: '80'
    sysctl_set: yes
    state: present
    reload: yes
  become: true

- name: Configure firewalld
  firewalld:
    port: '{{ item }}'
    state: enabled
    immediate: true
    permanent: true
  loop:
    - 80/tcp
    - 443/tcp
  become: true

- name: Install systemd service
  copy:
    src: heimdall.service
    dest: '{{ configdir }}/systemd/user/heimdall.service'
    mode: 0644

- name: Enable systemd service
  systemd:
    name: heimdall.service
    scope: user
    state: started
    enabled: true
    daemon_reload: true
