- name: Check existence of kitty terminfo
  stat:
    path: /usr/share/terminfo/x/xterm-kitty
  register: kitty_terminfo
  delegate_to: localhost

- name: Copy kitty terminfo
  block:
    - name: Create terminfo user directory
      file:
        path: "{{ homedir }}/.terminfo/x"
        state: directory

    - name: Copy xterm-kitty
      copy:
        src: /usr/share/terminfo/x/xterm-kitty
        dest: "{{ homedir }}/.terminfo/x"
  when: kitty_terminfo.stat.exists
