- name: Install epel-release
  dnf: name=epel-release
  become: true

- name: Enable toolboxcutter copr repo
  command: dnf copr enable -y jcrd/toolboxcutter
  become: true

- name: Install base packages
  dnf:
    name:
      - git
      - htop
      - lm_sensors
      - make
      - neovim
      - podman
      - psmisc
      - ranger
      - tmux
      - toolboxcutter
      - zsh
  become: true

- name: Set zsh as user shell
  user:
    name: "{{ ansible_user_id }}"
    shell: /usr/bin/zsh
  become: true

- name: Enable loginctl linger
  command: loginctl enable-linger {{ ansible_user_id }}

- name: Enable sshd pubkey authentication
  lineinfile:
    path: /etc/ssh/sshd_config
    line: "PubkeyAuthentication yes"
  become: true

- name: Create ssh directory with correct permissions
  file:
    path: "{{ homedir }}/.ssh"
    state: directory
    mode: 0700

- name: Create systemd user directory
  file:
    path: "{{ configdir }}/systemd/user"
    state: directory

- name: Enable cockpit
  systemd:
    name: cockpit.socket
    state: started
    enabled: true

- name: Install cockpit easymode config
  copy:
    src: cockpit.yml
    dest: "{{ easymodeconfig }}/"
